### PR TITLE
fix: return of useless function

### PR DESCRIPTION
**Pull request by romanthekat**
sorry for the hustle :)

#2 removed 'useless' function. it was apparently referenced, I missed that.
I wasn't able to reproduce a problem caused by this change, but generally an attempt to call non-existent function will fail. 

so that I returned the 'useless' function back, and renamed it to 'doNothing' to explicitly highlight what it does.
it is also fun to have a separate function to do just nothing :)

### CODE REVIEW

**Comment by romanthekat** [comment]
latest build file: [sudoku.pdx.zip](https://github.com/mattie-dev/playdate_sudoku/files/13063983/sudoku.pdx.zip)

**Comment by mattie-dev** [comment]
Im so glad to hear you like the game and thank you again so much for all your help and bug fixes / improvements!

**Comment by mattie-dev** [comment]
by the way I have updated the download on itch.io to reflect the new changes you have made!

**Comment by romanthekat** [comment]
> by the way I have updated the download on itch.io to reflect the new changes you have made!  

awesome, thank you =^_^=

**Pull request merged**
